name: Debug Punkt - Quick Sample

on:
  workflow_dispatch:  # not scheduled, only runs when manually triggered

jobs:
  debug-update:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'

    - name: Install dependencies 
      run: |
        python -m pip install --upgrade pip 
        pip install validate_punkt_requirements.txt #1
        pip install lxml[html_clean]

    - name: Run Enterprise Risk News script
      run: |
        echo "Running DEBUG-validate_punkt.py..." #2
        python DEBUG-validate_punkt.py || echo "DEBUG-validate_punkt.py failed!" #3

    - name: Check for changes
      id: check_changes
      run: |
        git status
        git diff --stat
        git status --porcelain
        if [[ -z $(git status --porcelain) ]]; then
          echo "No changes detected."
          echo "has_changes=false" >> $GITHUB_ENV
        else
          echo "Changes detected."
          echo "has_changes=true" >> $GITHUB_ENV
        fi

    - name: Push updates
      if: env.has_changes == 'true'
      run: |
        git config --global user.name "GitHub Actions Bot"
        git config --global user.email "noreply@github.com"
        git stash
        git pull --rebase origin main
        git stash pop || echo "No stashed changes to apply"
        git add .
        git commit -m "Manual debug run: $(date)" || echo "No changes to commit"
        git push origin main || echo "Git push failed!"
